/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include "gui.h"

// GListeners
GListener gl;

// GHandles
GHandle ghContainerHome;
GHandle lbl_temp;
GHandle lbl_status;
GHandle lbl_day;
GHandle lbl_time;

// Fonts
font_t ugfx_font_2;

static void createPageHome(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);


	// create container widget: ghContainerHome
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 128;
	wi.g.height = 64;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerHome = gwinContainerCreate(0, &wi, 0);

	// Create label widget: lbl_temp
	wi.g.show = TRUE;
	wi.g.x = 8;
	wi.g.y = 16;
	wi.g.width = 110;
	wi.g.height = 16;
	wi.g.parent = ghContainerHome;
	wi.text = "Label1";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	lbl_temp = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(lbl_temp, FALSE);

	// Create label widget: lbl_status
	wi.g.show = TRUE;
	wi.g.x = 8;
	wi.g.y = 0;
	wi.g.width = 32;
	wi.g.height = 16;
	wi.g.parent = ghContainerHome;
	wi.text = "Label2";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	lbl_status = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(lbl_status, FALSE);

	// Create label widget: lbl_day
	wi.g.show = TRUE;
	wi.g.x = 8;
	wi.g.y = 32;
	wi.g.width = 120;
	wi.g.height = 16;
	wi.g.parent = ghContainerHome;
	wi.text = "Label3";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	lbl_day = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(lbl_day, FALSE);

	// Create label widget: lbl_time
	wi.g.show = TRUE;
	wi.g.x = 8;
	wi.g.y = 48;
	wi.g.width = 120;
	wi.g.height = 16;
	wi.g.parent = ghContainerHome;
	wi.text = "Label4";
	wi.customDraw = gwinLabelDrawJustifiedLeft;
	wi.customParam = 0;
	wi.customStyle = 0;
	lbl_time = gwinLabelCreate(0, &wi);
	gwinLabelSetBorder(lbl_time, FALSE);
}

void guiShowPage(unsigned pageIndex)
{
	// Hide all pages
	gwinHide(ghContainerHome);

	// Show page selected page
	switch (pageIndex) {
	case 0:
		gwinShow(ghContainerHome);
		break;

	default:
		break;
	}
}

void guiCreate(void)
{
	GWidgetInit wi;

	// Prepare fonts
	ugfx_font_2 = gdispOpenFont("UI2");

	// Prepare images

	// GWIN settings
	gwinWidgetClearInit(&wi);
	gwinSetDefaultFont(ugfx_font_2);
	gwinSetDefaultStyle(&WhiteWidgetStyle, FALSE);
	gwinSetDefaultColor(Black);
	gwinSetDefaultBgColor(White);

	// Create all the display pages
	createPageHome();

	// Select the default display page
	guiShowPage(0);

}

void guiEventLoop(void)
{
	GEvent* pe;

	while (1) {
		// Get an event
		pe = geventEventWait(&gl, 0);
		switch (pe->type) {
		}

	}
}

